---
- block:
  - name: homebrew update
    homebrew:
      update_homebrew: yes

  - name: Tap external Homebrew repositories
    homebrew_tap: 
      name: "{{ item }}"
      state: present
    with_items: "{{ taps }}"

  - name: Install Homebrew packages
    homebrew: 
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ packages }}"
  
  tags:
    - homebrew