---
- block:
  - name: homebrew cask packages install
    homebrew_cask: 
      name: "{{ item.name }}"
      state: installed
    environment:
      HOMEBREW_CASK_OPTS: "--appdir=/Applications"
    with_items: "{{ cask_packages }}"
  
  tags:
    - homebrew_cask